# Generated by Django 2.0.5 on 2018-06-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='avg_position',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap_speed',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='driver_rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='elapsed_time',
            field=models.IntegerField(),
        ),
    ]
