# Generated by Django 2.0.5 on 2018-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='avg_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap_speed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='driver_rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='result',
            name='elapsed_time',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='avg_finish_position',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='avg_laps_completed',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='standing',
            name='avg_start_postion',
            field=models.FloatField(),
        ),
    ]
