# Generated by Django 2.0.5 on 2018-06-18 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0002_auto_20180618_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='actual_distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='avg_speed',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='caution_laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='cautions',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='condition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='distance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='elapsed_time',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='flags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='laps_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='lead_changes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='race_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='victory_margin',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
    ]
