# Generated by Django 2.0.5 on 2018-06-18 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0002_auto_20180617_0007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='race_number',
        ),
    ]
