# Generated by Django 2.0.5 on 2018-06-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0002_auto_20180613_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('actual_distance', models.IntegerField()),
                ('avg_speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('caution_laps', models.IntegerField()),
                ('cautions', models.CharField(max_length=250)),
                ('condition', models.CharField(max_length=250)),
                ('distance', models.IntegerField()),
                ('elapsed_time', models.CharField(max_length=250)),
                ('flags', models.IntegerField()),
                ('laps', models.IntegerField()),
                ('laps_completed', models.IntegerField()),
                ('lead_changes', models.IntegerField()),
                ('race_number', models.IntegerField()),
                ('scheduled_time', models.DateTimeField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('victory_margin', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_position', models.DecimalField(decimal_places=3, max_digits=6)),
                ('avg_speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('best_lap', models.IntegerField()),
                ('best_lap_speed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('best_lap_time', models.DecimalField(decimal_places=3, max_digits=6)),
                ('bonus_points', models.IntegerField()),
                ('driver_rating', models.DecimalField(decimal_places=3, max_digits=6)),
                ('elapsed_time', models.DecimalField(decimal_places=3, max_digits=6)),
                ('fastest_laps', models.IntegerField()),
                ('laps_completed', models.IntegerField()),
                ('laps_led', models.IntegerField()),
                ('passes_made', models.IntegerField()),
                ('passing_differential', models.IntegerField()),
                ('penalty_points', models.IntegerField()),
                ('pit_stops', models.IntegerField()),
                ('points', models.IntegerField()),
                ('position', models.IntegerField()),
                ('quality_passes', models.IntegerField()),
                ('start_position', models.IntegerField()),
                ('status', models.CharField(max_length=250)),
                ('times_led', models.IntegerField()),
                ('times_passed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_finish_position', models.DecimalField(decimal_places=3, max_digits=6)),
                ('avg_laps_completed', models.DecimalField(decimal_places=3, max_digits=6)),
                ('avg_start_postion', models.DecimalField(decimal_places=3, max_digits=6)),
                ('chase_bonus', models.IntegerField()),
                ('dnf', models.IntegerField()),
                ('full_name', models.CharField(max_length=200)),
                ('in_chase', models.BooleanField()),
                ('laps_completed', models.IntegerField()),
                ('laps_led', models.IntegerField()),
                ('laps_led_pct', models.IntegerField()),
                ('points', models.IntegerField()),
                ('poles', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('stage_wins', models.IntegerField()),
                ('starts', models.IntegerField()),
                ('status', models.CharField(max_length=200)),
                ('top_5', models.IntegerField()),
                ('top_10', models.IntegerField()),
                ('top_15', models.IntegerField()),
                ('top_20', models.IntegerField()),
                ('wins', models.IntegerField()),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crew_chief', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('sponsors', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterModelOptions(
            name='driver',
            options={'ordering': ['last_name']},
        ),
        migrations.AddField(
            model_name='driver',
            name='car_number',
            field=models.IntegerField(default=1967),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='gender',
            field=models.CharField(default='m', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='height',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='hobbies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='last_name',
            field=models.CharField(default='namelast', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='residence',
            field=models.CharField(default='123 fake st', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='rookie_year',
            field=models.IntegerField(default=1937),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default=1980, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='twitter',
            field=models.CharField(default='@improllydeadnow', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='standing',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='racechart.Driver'),
        ),
        migrations.AddField(
            model_name='result',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='racechart.Driver'),
        ),
        migrations.AddField(
            model_name='result',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='racechart.Race'),
        ),
        migrations.AddField(
            model_name='race',
            name='drivers',
            field=models.ManyToManyField(related_name='races', to='racechart.Driver'),
        ),
    ]
