# Generated by Django 2.0.5 on 2018-06-18 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0003_remove_race_race_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='race',
            name='flags',
        ),
    ]
