# Generated by Django 2.0.5 on 2018-06-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0003_auto_20180614_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
