# Generated by Django 2.0.5 on 2018-06-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0003_auto_20180618_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='actual_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='victory_margin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
