# Generated by Django 2.0.5 on 2018-08-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0004_auto_20180618_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='track',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='best_lap_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='bonus_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='driver_rating',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='elapsed_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='fastest_laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='laps_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='laps_led',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='passes_made',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='passing_differential',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='penalty_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='pit_stops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='quality_passes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='start_position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='status',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='times_led',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='times_passed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='avg_finish_position',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='avg_laps_completed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='avg_start_postion',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='dnf',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='full_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='laps_completed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='laps_led',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='laps_led_pct',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='poles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='stage_wins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='starts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='top_10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='top_15',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='top_20',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='top_5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='standing',
            name='wins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
