# Generated by Django 2.0.5 on 2018-06-14 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0004_auto_20180614_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
