# Generated by Django 2.0.5 on 2018-06-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0004_remove_race_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='flags',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
