# Generated by Django 2.0.5 on 2018-06-14 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0005_auto_20180614_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
