# Generated by Django 2.0.5 on 2018-08-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0005_auto_20180802_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='track',
            field=models.CharField(default='value', max_length=250),
            preserve_default=False,
        ),
    ]
