# Generated by Django 2.0.5 on 2018-06-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0006_auto_20180614_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
