# Generated by Django 2.0.5 on 2018-06-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0008_auto_20180614_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
