# Generated by Django 2.0.5 on 2018-06-14 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0011_auto_20180614_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='residence',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='twitter',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
