# Generated by Django 2.0.5 on 2018-06-14 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0012_auto_20180614_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='car_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
