# Generated by Django 2.0.5 on 2018-06-15 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0013_auto_20180614_2310'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='owner',
            field=models.CharField(default='Jeebus chrissman', max_length=200),
            preserve_default=False,
        ),
    ]
