# Generated by Django 2.0.5 on 2018-06-15 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0014_team_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crew_chief',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='manufacturer',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='team',
            name='sponsors',
            field=models.CharField(max_length=1000),
        ),
    ]
