# Generated by Django 2.0.5 on 2018-06-15 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('racechart', '0015_auto_20180615_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='crew_chief',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='owner',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sponsors',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
